export function getCategoryIcon(category: string | null): string {
  if (!category) return ''

  const categoryMap: Record<string, string> = {
    Income: '🤑',
    Salary: '🤑',
    Retirement: '🤑',
    'Entrepreneurial activities': '💲',
    'Government aid': '🤑',
    'Non-recurring income': '🤑',
    'Loans and financing': '💰',
    'Late payment and overdraft costs': '💰',
    'Interests charged': '💰',
    Financing: '💰',
    'Real estate financing': '💰',
    'Vehicle financing': '🚗',
    'Student loan': '💰',
    Loans: '💰',
    Investments: '💹',
    'Automatic investment': '💹',
    'Fixed income': '💹',
    'Mutual funds': '💰',
    'Variable income': '💰',
    Margin: '💰',
    'Proceeds interests and dividends': '',
    Pension: '💰',
    'Same person transfer': '',
    'Same person transfer - CASH': '',
    'Same person transfer - PIX': '',
    'Same person transfer - TED': '',
    Transfers: '',
    'Transfer - Bank Slip': '',
    'Transfer - Cash': '',
    'Transfer - Check': '',
    'Transfer - DOC': '',
    'Transfer - Foreign Exchange': '',
    'Transfer - Internal': '',
    'Transfer - PIX': '',
    'Transfer - TED': '',
    'Third party transfers': '',
    'Third party transfer - Bank Slip': '',
    'Third party transfer - Debit Card': '',
    'Third party transfer - DOC': '',
    'Third party transfer - PIX': '',
    'Third party transfer - TED': '',
    'Credit card payment': '💳',
    'Legal obligations': '💳',
    'Blocked balances': '💳',
    Alimony: '💰',
    Services: '🧹',
    Telecommunications: '📞',
    Internet: '🌐',
    Mobile: '📱',
    TV: '📺',
    Education: '🎓',
    'Online Courses': '🎓',
    University: '🎓',
    School: '🏫',
    Kindergarten: '🏫',
    'Wellness and fitness': '🏋️',
    'Gyms and fitness centers': '🏋️',
    'Sports practice': '🏋️',
    Wellness: '🏋️',
    Tickets: '💰',
    'Stadiums and arenas': '💰',
    'Landmarks and museums': '💰',
    'Cinema, theater and concerts': '💰',
    Shopping: '🛍️',
    'Online shopping': '🛍️',
    Electronics: '💻',
    'Pet supplies and vet': '💰',
    Clothing: '👗',
    'Kids and toys': '👶',
    Bookstore: '📚',
    'Sports goods': '💰',
    'Office supplies': '💰',
    Cashback: '💰',
    'Digital services': '💻',
    Gaming: '💰',
    'Video streaming': '🎥',
    'Music streaming': '🎶',
    Groceries: '🛒',
    'Food and drinks': '🥩',
    'Eating out': '🍔',
    'Food delivery': '🍔',
    Travel: '💰',
    'Airport and airlines': '💰',
    Accomodation: '💰',
    'Mileage programs': '💰',
    'Bus tickets': '💰',
    Donations: '💰',
    Gambling: '💰',
    Lottery: '💰',
    'Online bet': '💰',
    Taxes: '💰',
    'Income taxes': '💰',
    'Taxes on investments': '💰',
    'Tax on financial operations': '💰',
    'Bank fees': '💰',
    'Account fees': '💰',
    'Wire transfer fees and ATM fees': '💰',
    'Credit card fees': '💰',
    Housing: '🏠',
    Rent: '🏠',
    Utilities: '💰',
    Water: '💧',
    Electricity: '🔌',
    Gas: '',
    Houseware: '💰',
    'Urban land and building tax': '💰',
    Healthcare: '🏥',
    Dentist: '🦷',
    Pharmacy: '💊',
    Optometry: '👀',
    'Hospital clinics and labs': '🏥',
    Transportation: '🚗',
    'Taxi and ride-hailing': '🚗',
    'Public transportation': '🚗',
    'Car rental': '🚗',
    Bicycle: '🚲',
    Automotive: '🚗',
    'Gas stations': '🚗',
    Parking: '🅿️',
    'Tolls and in vehicle payment': '🚗',
    'Vehicle ownership taxes and fees': '🚗',
    'Vehicle maintenance': '🚗',
    'Traffic tickets': '🚗',
    Insurance: '🦺',
    'Life insurance': '🦺',
    'Home insurance': '🦺',
    'Health insurance': '🦺',
    'Vehicle insurance': '🦺',
    Leisure: '🎉',
    Other: '',
  }

  return categoryMap[category] || ''
}
